### ISSUE TITLE
Logs me back in, but says 404 | not found

### ISSUE THREAD

**Issue by MarcuzAizen** [kertnik05/LVA#40]
**Describe the bug**

After updating or cloning the project,
after logging-in and out few minutes later, it logs me out, I signed in but it displays "404 | not found".

**To Reproduce**

1. Go to 'log-in page'
2.  'log-in as registrar or teacher'
3. it displays "404 | not found"

**Expected behavior**
i could still log in anytime.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: linux ubuntu
 - Browser chrome and firefox

**Comment by kertnik05** [comment]
@MarcuzAizen I can login fine with both roles using your forked repo.

**Comment by kertnik05** [comment]
@MarcuzAizen try to comment out this line:
https://github.com/kertnik05/LVA/blob/f2e9a770b20f611091ef2ed6385cac380c682354/app/Http/Controllers/Auth/Employee/LoginController.php#L18
