### ISSUE TITLE
i can't access the data using {{schedule.grades.mark}}

### ISSUE THREAD

**Issue by MarcuzAizen** [kertnik05/LVA#47]
this are the data that i try to view in postman, in schedule api, i can't access the data " schedule.grades.mark ", which i notice is inside an object in an array,, I can't access it using the double mustache <td>{{schedule.grades.mark}}</td>.
 

"data": [
        {
            "id": 3,
            "acad_year_id": 1,
            "teacher_id": 5,
            "section_id": 8,
            "prospectus_id": 5,
            "day": "H",
            "time_start": "03:45:53",
            "time_end": "07:51:57",
            "acad_year": {
                "id": 1,
                "start": 1997,
                "end": 1998,
                "created_at": "2020-12-01T06:49:39.000000Z",
                "updated_at": "2020-12-01T06:49:39.000000Z",
                "deleted_at": null
            },
            "teacher": {
                "id": 5,
                "role_id": 5,
                "first_name": "Joana",
                "middle_name": null,
                "last_name": "BAHRINGER",
                "suffix": null,
                "sex": "M",
                "birthdate": "1971-09-02",
                "contact_number": "09952340458",
                "purok": "sit",
                "barangay": "dolore",
                "city": "laboriosam",
                "province": "totam",
                "username": "teacher"
            },
            "grades": [
                {
                    "id": 3,
                    "enroll_id": 1,
                    "schedule_id": 3,
                    "mark": 4,
                    "quarter_sem": 2
                }
            ],
            "section": {
                "id": 8,
                "track_id": 2,
                "name": "Jack Dare",
                "capacity": 48,
                "track": {
                    "id": 2,
                    "name": "HUMMS",
                    "description": "Id accusantium animi et sed quam optio.",
                    "grade_level": 12
                },
                "enrolls": [
                    {
                        "id": 5,
                        "registrar_id": 2,
                        "student_id": 4,
                        "acad_year_id": 2,
                        "section_id": 8,
                        "created_at": "2020-12-01T06:49:46.000000Z",
                        "updated_at": "2020-12-01T06:49:46.000000Z",
                        "deleted_at": null,
                        "student": {
                            "id": 4,
                            "student_remark_id": null,
                            "lrn": "241260110271",
                            "first_name": "Pierre",
                            "middle_name": "Moore",
                            "last_name": "JACOBI",
                            "suffix": null,
                            "sex": "F",
                            "birthdate": "1980-11-15",
                            "mother_tongue": "Ut",
                            "contact_number": "09710925641",
                            "previous_school": "White-Bruen",
                            "ethnic": "Qui",
                            "religion": "Dolore",
                            "purok": "772",
                            "barangay": "Garrick Keys",
                            "city": "Port Eddside",
                            "province": "New Hampshire",
                            "username": "kunze.raymundo",
                            "full_name": "JACOBI, Pierre, Moore"
                        }
                    },
                    {
                        "id": 7,
                        "registrar_id": 2,
                        "student_id": 8,
                        "acad_year_id": 6,
                        "section_id": 8,
                        "created_at": "2020-12-01T06:49:47.000000Z",
                        "updated_at": "2020-12-01T06:49:47.000000Z",
                        "deleted_at": null,
                        "student": {
                            "id": 8,
                            "student_remark_id": null,
                            "lrn": "742165731890",
                            "first_name": "Carli",
                            "middle_name": "Beahan",
                            "last_name": "KREIGER",
                            "suffix": null,
                            "sex": "F",
                            "birthdate": "2002-03-15",
                            "mother_tongue": "Et",
                            "contact_number": "09760095834",
                            "previous_school": "Lockman, Wilkinson and Conroy",
                            "ethnic": "Ut",
                            "religion": "Aliquid",
                            "purok": "96163",
                            "barangay": "Leffler Corners",
                            "city": "East Olinfort",
                            "province": "Michigan",
                            "username": "wferry",
                            "full_name": "KREIGER, Carli, Beahan"
                        }
                    },
                    {
                        "id": 9,
                        "registrar_id": 2,
                        "student_id": 1,
                        "acad_year_id": 4,
                        "section_id": 8,
                        "created_at": "2020-12-01T06:49:47.000000Z",
                        "updated_at": "2020-12-01T06:49:47.000000Z",
                        "deleted_at": null,
                        "student": {
                            "id": 1,
                            "student_remark_id": 3,
                            "lrn": "955352403941",
                            "first_name": "Justina",
                            "middle_name": null,
                            "last_name": "ROBEL",
                            "suffix": "III",
                            "sex": "F",
                            "birthdate": "2001-05-25",
                            "mother_tongue": "Omnis",
                            "contact_number": "09744214960",
                            "previous_school": "Rippin, Considine and Murazik",
                            "ethnic": "Reiciendis",
                            "religion": "Temporibus",
                            "purok": "98544",
                            "barangay": "Nathen Springs",
                            "city": "Ferrybury",
                            "province": "Minnesota",
                            "username": "conn.isaiah",
                            "full_name": "ROBEL, Justina, III"
                        }
                    }
                ]
            },
            "prospectus": {
                "id": 5,
                "track_id": 3,
                "subject_id": 1,
                "sem_to_offer": null,
                "created_at": "2020-12-01T06:49:44.000000Z",
                "updated_at": "2020-12-01T06:49:44.000000Z",
                "subject": {
                    "id": 1,
                    "code": "47231351",
                    "description": "Aut assumenda adipisci neque quasi exercitationem aspernatur.",
                    "unit": 8
                }
            }
        },

**Comment by kertnik05** [comment]
@MarcuzAizen please show a snippet of your code and how did you access it the data your trying to get.

**Comment by kertnik05** [comment]
@MarcuzAizen use https://carbon.now.sh/ for your code snippets for better readability

**Comment by MarcuzAizen** [comment]
![carbon](https://user-images.githubusercontent.com/38231438/101275224-f2c20100-37de-11eb-9fd0-63ff58b8136f.png)

**Comment by MarcuzAizen** [comment]
@kertnik05 
![carbon(1)](https://user-images.githubusercontent.com/38231438/101275525-3e75aa00-37e1-11eb-9891-39dea0a8075f.png)

**Comment by kertnik05** [comment]
@MarcuzAizen you're using the wrong api endpoint in your loadSchedules() function

**Comment by MarcuzAizen** [comment]
@kertnik05 may you give me an example? this what comes to my mind

![carbon](https://user-images.githubusercontent.com/38231438/101275644-1cc8f280-37e2-11eb-8bd2-2bf114a20de7.png)

**Comment by kertnik05** [comment]
> @kertnik05 may you give me an example? this is what pops-up to my mind
> 
> ![carbon](https://user-images.githubusercontent.com/38231438/101275644-1cc8f280-37e2-11eb-8bd2-2bf114a20de7.png)

@MarcuzAizen that api endpoint returns all schedules data for all teachers. You want to use the api endpoint that returns the schedule data for the current logged in teacher

**Comment by MarcuzAizen** [comment]
@kertnik05 well, i don't know that "?page={page}" either and what it does, i don't know how to put an endpoint,, all i know is that, it works.

**Comment by kertnik05** [comment]
@MarcuzAizen what I mean of endpoint is api route.

**Comment by kertnik05** [comment]
@MarcuzAizen so you're using the wrong api route

**Comment by kertnik05** [comment]
@MarcuzAizen `/teacher/api/schedule-grade` this is the api endpoint/route you should be using

**Comment by MarcuzAizen** [comment]
@kertnik05 Owh I see, i thought same routes i use during making an api

**Comment by kertnik05** [comment]
@MarcuzAizen tha'ts why I asked you to review the PR for that

**Comment by MarcuzAizen** [comment]
@kertnik05 yeah but i chose to approved that for a reason. there are a lot of things which i don't understand and confuses me, even if you try to explain it, i would still end-up forgetting all of those. so i would rather ask during the process instead.

**Comment by kertnik05** [comment]
@MarcuzAizen it's okay. It's a good thing to ask. Just ask if you have any questions, brad.
